title: Building IIIF Manifests with File Analyzer
description: "Generate a rich IIIF experience from your existing metadata"
baseurl: "/File-Analyzer-Test-Data" 
url: "http://Georgetown-University-Libraries.github.io/File-Analyzer-Test-Data" 
tagline: Re-use your metadata
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: UA-297597-14

# --------------------------------
# Custom additions for the tutorial navigation bar
# --------------------------------

# src_path - used to construct nested links to code files
src_path: "https://github.com/Georgetown-University-Libraries/File-Analyzer-Test-Data/tree/gh-pages"

# nav_style: menu or button
nav_style: button
nav:
  - {name: Intro, path: "/intro"}
  - {name: "Setup", path: "/setup"}
  - {name: "Basic Manifest", path: "/demo1"}
  - {name: "Item Metadata", path: "/demo2"}
  - {name: "Date Ranges", path: "/demo3"}
  - {name: "Folder Ranges", path: "/demo4"}
  - {name: "EAD+Folder Ranges", path: "/demo5"}
  - {name: "EAD Ranges", path: "/demo6"}
  - {name: "EAD Ranges + DAO’s", path: "/demo7"}
  - {name: "CSV Metadata", path: "/demo8"}
  - {name: "Collection Manifests", path: "/demo9"}
  - {name: "Custom Code", path: "/code"}

